let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Zoo-Shirt",
    price: 25,
    desc: "Kanazawa Zoo Official T-shirt.",
    img: "./image/tshirt.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Zoo-Sweater",
    price: 45,
    desc: "Kanazawa Zoo Official Sweater.",
    img: "image/sweater.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Candy",
    price: 5,
    desc: "Zoo Candies.",
    img: "image/candy.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Zoo Calendar",
    price: 10,
    desc: "2025 Kanazawa Zoo Calendar.",
    img: "image/calendar.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Plush",
    price: 20,
    desc: "White Tiger Plush.",
    img: "image/whitetigerplush.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Key Chain",
    price: 8,
    desc: "Kanazawa Zoo key chain.",
    img: "image/snake.webp",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Coffee Mug",
    price: 15,
    desc: "Kanazawa Zoo coffee mug.",
    img: "image/coffeemug.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Zoo Car",
    price: 25,
    desc: "Kanazawa Zoo car kids toy.",
    img: "image/zoocar.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Kanazawa Zoo monkey shoe",
    price: 5,
    desc: "2025 Zoo Charm.",
    img: "image/zooshoe.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Snake!",
    price: 15,
    desc: "Realistic toy snake.",
    img: "image/snaketoy.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Kanazawa Zoo hat",
    price: 20,
    desc: "Official Kazazawa Zoo hat.",
    img: "image/zoohat.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Zoo poster",
    price: 3,
    desc: "Kanazawa Zoo poster.",
    img: "image/zooposter.jpg",
  },
];
